version: '2'
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      SPRING_ENVIRONMENT: 'development'
    ports:
      - 8000:8000
#    volumes:
#      - ./backend/:/usr/src/app/
    links:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: BizToi
      MYSQL_USER: biztoi
      MYSQL_PASSWORD: biztoi
      MYSQL_ROOT_PASSWORD: biztoi
    ports:
      - 3307:3306
