spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ProteinCounter
    username: root
    driverClassName: com.mysql.cj.jdbc.Driver

server:
  port: 8000
  servlet:
    context-path: /api

urls:
  cognito: https://biztoi-dev.auth.us-east-1.amazoncognito.com
endpoints:
  authorize: ${urls.cognito}/oauth2/authorize?response_type=code&client_id=${cognito.client}&redirect_uri=${cognito.callback}
  token: ${urls.cognito}/oauth2/token
cognito:
  client: 6vmckgmdr0qa3mopaadndr3lba
  secret: 5d1o6s1aq1aqlt8q206eg4mijvj01tjm68aanhdjs5nlen9b3qc
  callback: http://localhost:3000/about
  keys: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_ff1SlJRo2/.well-known/jwks.json

#cloud:
#  aws:
#    stack:
#      # CloudFormationのstack名を自動収集しない
#      auto: false
#    region:
#      # EC2のmetadataを自動収集しない
#      auto: false
#      static: ap-northeast-1